### ISSUE TITLE
Multiple dashboard issue

### ISSUE THREAD

**Issue by AxelVllR** [Orbitale/SvelteAdmin#6]
We're currently trying to implement a dynamic menu based on user roles.

However, when I try to make the "sidemenu" links dynamic in the instantiation of the DashboardDefinition class, or to define this dashboard twice (with a condition like if role_utilisateur == 'admin' I use dashboard1 otherwise I use dashboard2) I get an error like: "cannot redeclare class ...".

Here are the notes I took:

The CrudDefinition class let us define all our dashboard constants like site title, menus, themes, etc.

We instantiate this class when the app is compiled (according to my observations). After instantiation, it's apparently no longer possible to update it, as several attempts have failed.

After investigation, here's the class definition in the svelteAdmin bundle:

```
export declare class DashboardDefinition {
    readonly adminConfig: AdminConfig;
    readonly cruds: Array<CrudDefinition<unknown>>;
    readonly sideMenu: Array<MenuLink>;
    readonly topLeftMenu: Array<MenuLink>;
    readonly topRightMenu: Array<MenuLink>;
    readonly localeDictionaries: Dictionaries;
    readonly options: {};

    constructor(options: DashboardDefinitionOptions);

    getFirstActionUrl(): string;

    private checkUniqueCruds;
}
```

Please let us know when this is fixed.

**Comment by Pierstoval** [comment]
There is no workaround for now, but there is a way this can be implemented in the `Dashboard` class, and is something I already planned (without having the time yet), which is to replace the current static menus with dynamic ones, with the help of Svelte stores.

* Create a readonly `stores` property in Dashboard
* Its type has to be a key->value object. Keys will be specific strings (one for each menu), and values types will be `Writable` (with capital W, this type comes from Svelte stores typescript definitions).
* When constructed, the Dashboard will create one `writable()` store for each of these properties, containing the configured menus.
* All templates that use the current menu properties will have to instead use the store version, using Svelte's store syntax
* Current static menus properties might have to be removed, but in the meantime, I suggest to make them private, non-readonly, and use public getters to get the current value from the store (using Svelte's `get()` function from the stores module), and triggering a deprecation error with console.log.

I don't have any details about when I can work on it yet, but with these instructions, I hope you can do it, let me know if you need more details about how to implement it 👍

**Comment by axel-simpliciti** [comment]
Thanks for your reply. However, based on what you've just said, it's equivalent to creating a store to register the entire "**Dashboard**" object or just the "**sideMenu**", "**topLeftMenu**" and "**topRightMenu**" properties ?

Can you tell me more about this? If I understand correctly, for each menu I'll create a store to register the links in question, which I'll retrieve from each template that uses these properties ?

Maybe I'm wrong?

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by axel-simpliciti** [comment]
I made a draft code on my fork (WARNING: this is only a test version to check that we are on the same wavelength) :https://github.com/axel-simpliciti/SvelteAdmin/pull/1/files

**Comment by Pierstoval** [comment]
> Thanks for your reply. However, based on what you've just said, it's equivalent to creating a store to register the entire "**Dashboard**" object or just the "**sideMenu**", "**topLeftMenu**" and "**topRightMenu**" properties ?

No, what I think about is something like this:

```typescript
import {writable} from 'svelte/store';
import type {Writable} from 'svelte/store';

class DashboardDefinition {
    // ...
    public readonly stores: DashboardStores;

    constructor( /* ... */ ) {
        // ...
        this.stores = {
            sideMenu: writable(options.sideMenu);
            topLeftMenu: writable(options.topLeftMenu);
            topRightMenu: writable(options.topRightMenu);
        };
    }
    // ...
}

type DashboardStores = {
    sideMenu: Writable<Action[]>;
    topLeftMenu: Writable<Action[]>;
    topRightMenu: Writable<Action[]>;
};
```


It's important to note that these 3 properties are used in a few templates, and these templates should stop referring to `dashboard.sideMenu` and instead refer to it using Svelte's store syntax.

There's a small example here: https://svelte.dev/repl/2eb20f378cb64992aedfcecc3e268c52?version=4.2.11

Since the stores will be in the `dashboard.stores` property, you will have to create a constant to refer to the store in your `<script>`, just like in the example linked above.

**Comment by Pierstoval** [comment]
Added in [v0.14.0](https://github.com/Orbitale/SvelteAdmin/blob/main/CHANGELOG.md#v0140)

**Comment by Pierstoval** [comment]
You can now use the `dashboard.stores` property and update your menus whenever you want, as long as you have access to the `dashboard` object :tada: 

Example here:

```typescript
const dashboard = /* ... */;

const user = /* ... */;

const isAdmin = user.roles.filter(role => role === 'ROLE_ADMIN').length > 0;

if (isAdmin) {
    dashboard.stores.topRightMenu.update((links: Array<MenuLink>) => {
        return [...links, new UrlAction('Admin', '/admin')];
    });
}
```
